[[questions]]
question = "What color are 30% of the M&M's in a regular bag of M&M's?"
answers = ["Brown"]
alternatives = ["Red", "Yellow", "Blue"]

[[questions]]
question = "How many 'frikandellen' does the average Dutch person eat per year?"
answers = ["37"]
alternatives = ["42", "50", "1000"]

[[questions]]
question = "What is the English name for the Dutch pastry 'oliebol'?"
answers = ["Dutch Doughnut", "Donut"]
alternatives = [
"Stroopwafel",
"Hamburger"]

[[questions]]
question = "Where does the authentic champagne come from?"
answers = ["France"]
alternatives = ["United States", "Spain", "Portugal"]

[[questions]]
question = "Who blinks more often, men or women?"
answers = ["Women"]
alternatives = [
"Men",
"Both equally",
"Huh, blink?"]

[[questions]]
question = "What grape varieties are used in a regular champagne?"
answers = ["Chardonnay, Pinot Noir, Pinot Meunier"]
alternatives = ["Sauvignon Blanc and Pinot Noir", "Chardonnay", "Chardonnay and Pinot Noir"]

[[questions]]
question = "How long does it take the ISS to orbit the Earth?"
answers = ["1 hour and 30 minutes", "1.5 hours"]
alternatives = [
"30 minutes",
"5 hours",
"12 hours",
]

[[questions]]
question = "What is the hottest pepper in the world?"
answers = ["Carolina Reaper"]
alternatives = [
"Ghost Pepper (Bhut Jolokia)",
"Trinidad Moruga Scorpion",
"Naga Viper",
]

[[questions]]
question = "What is the main ingredient in beer?"
answers = ["Water"]
alternatives = ["Hops", "Alcohol", "Grain"]

[[questions]]
question = "How many senses does a human have?"
answers = ["5"]
alternatives = ["6", "7", "4"]

[[questions]]
question = "In which country are the most ice creams eaten?"
answers = ["Norway"]
alternatives = ["United States", "Netherlands"]

[[questions]]
question = "Where is the highest alcohol consumption per capita in the world?"
answers = ["Moldova"]
alternatives = [
"Russia",
"Netherlands",
"France",
]

[[questions]]
question = "Which Italian dish literally means 'pick me up'?"
answers = ["Tiramisu"]
alternatives = [
"Pizza",
"Cannoli",
"Panna Cotta"]